version: '3'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/app/coredns-consulkv-plugin
      - ../Corefile:/app/coredns/Corefile
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: /bin/sh -c "while sleep 1000; do :; done"

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0