version: '3'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - ${HOME}${USERPROFILE}/.ssh:/home/vscode/.ssh:ro
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: sleep infinity

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0