name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm, arm64]
        exclude:
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Get CoreDNS
      run: |
        git clone https://github.com/coredns/coredns.git
        cd coredns
        echo "consulkv:github.com/${{ github.repository }}" >> plugin.cfg

    - name: Build
      run: |
        cd coredns
        go get github.com/mwantia/coredns-consulkv-plugin
        go generate
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o coredns
      env:
        CGO_ENABLED: 0

    - name: Create archive
      run: |
        cd coredns
        zip coredns-consulkv-${{ matrix.goos }}-${{ matrix.goarch }}.zip coredns

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: coredns-consulkv-${{ matrix.goos }}-${{ matrix.goarch }}
        path: coredns/coredns-consulkv-${{ matrix.goos }}-${{ matrix.goarch }}.*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "Release ${{ github.ref_name }}"

    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for asset in coredns-consulkv-*/*; do
          gh release upload ${{ github.ref_name }} "$asset" --clobber
        done
